version: "3.9"

services:
  backend:
    build:
      context: ./opportunity_finder_backend
      dockerfile: Dockerfile
    env_file:
      - ./opportunity_finder_backend/.env
    environment:
      DATABASE_URL: postgres://opportunity_finder:opportunity_finder@db:5432/opportunity_finder
      CELERY_BROKER_URL: redis://redis:6379/0
      DJANGO_DEBUG: "1"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,backend"
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    volumes:
    - ./opportunity_finder_backend/db_dump.json:/app/db_dump.json

  celery-worker:
    build:
      context: ./opportunity_finder_backend
      dockerfile: Dockerfile
    env_file:
      - ./opportunity_finder_backend/.env
    environment:
      DATABASE_URL: postgres://opportunity_finder:opportunity_finder@db:5432/opportunity_finder
      CELERY_BROKER_URL: redis://redis:6379/0
      DJANGO_DEBUG: "1"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,backend"
    depends_on:
      - db
      - redis
    command: ["celery", "-A", "opportunity_finder", "worker", "--loglevel=INFO", "--pool=solo"]

  celery-beat:
    build:
      context: ./opportunity_finder_backend
      dockerfile: Dockerfile
    env_file:
      - ./opportunity_finder_backend/.env
    environment:
      DATABASE_URL: postgres://opportunity_finder:opportunity_finder@db:5432/opportunity_finder
      CELERY_BROKER_URL: redis://redis:6379/0
      DJANGO_DEBUG: "1"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,backend"
    depends_on:
      - db
      - redis
    command: ["celery", "-A", "opportunity_finder", "beat", "--loglevel=INFO"]

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: opportunity_finder
      POSTGRES_USER: opportunity_finder
      POSTGRES_PASSWORD: opportunity_finder
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./opportunity_finder_frontend
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8000
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  pgdata: